import Head from "next/head";
import react,{ useEffect, useState } from "react";
import { useRouter } from "next/router";
import { PokemonIndex, PokemonProps } from "@/interface";
import { CountContext } from "@/context/context";
import { fetchPokemon, initStorage } from "@/function";

export default function Home(props: PokemonProps) {
  const router = useRouter();
  const [dataPokemons, setPokemon] = useState<PokemonIndex[]>([]);
  const [url, setUrl] = useState("https://pokeapi.co/api/v2/pokemon");
  const [offset, setOffset] = useState(0);
  const countContext = react.useContext(CountContext)

  const handleLoadMore = () => {
    dataFetch(`${url}?offset=${offset}&limit=20`);
    setOffset(offset + 20);
  };

  const dataFetch = async (url:string) => {
    const temp = await fetchPokemon(url);
    const newPokemon = temp.results;
    setPokemon([...dataPokemons, ...newPokemon]);
  }

  useEffect(() => {
    dataFetch(url);
    initStorage(countContext)
  }, []);
  
  return (
    <>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-4">
        <div className="row d-flex justify-content-center">
          {dataPokemons.map((pokemon: any) => {
            return (
              <div
                key={pokemon.name}
                className="col-md-5 d-flex justify-content-between mx-4 border rounded align-items-center py-1 my-2 border-secondary"
              >
                <div>
                  <span className="text-uppercase">{pokemon.name}&nbsp;</span>
                  {
                    JSON.parse(window.localStorage.getItem(pokemon.name) as any) ?(
                      <span>(owned:&nbsp;
                        {
                          JSON.parse(
                            window.localStorage.getItem(pokemon.name) as any
                          )?.length
                        }
                      )
                      </span>
                        
                    ):(
                      <span>(owned: 0)</span>
                    )
                  }
                </div>
                <button
                  className="btn btn-primary"
                  onClick={() => router.push(`/pokemon/${pokemon.name}`)}
                >
                  View
                </button>
              </div>
            )
          })}
        </div>
        <div className="my-2 align-items-center text-center">
          <button className="btn btn-secondary" onClick={handleLoadMore}>
            Load More
          </button>
        </div>
      </div>
    </>
  );
}
