import Head from 'next/head'
import Link from 'next/link';
import axios from 'axios';
import { GetServerSideProps } from 'next';
import API from '@/services';
import { useEffect, useState } from 'react';

interface Pokemon{
  name: string;
  url: string;
}

interface PokemonProps{
  count: number;
  next: string;
  previous: string;
  dataPokemons: Pokemon[];
}

export default function Home(props: PokemonProps) {
  const {dataPokemons} = props

  console.log(props)
  
  const [limit, setLimit] = useState(20);
  
  console.log(limit);
  const handleLoadMore = () => {
    setLimit(limit + 20);
  }

  useEffect(() => {
    
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-4">
        <div className="row">
          {/* <div className="col-5 d-flex justify-content-between mx-5 border rounded align-items-center py-1">
            <span>Bulbasaur</span>
            <Link href={"/"} className="btn btn-primary">View</Link>
          </div> */}
          {/* {dataPokemons.count} */}
          {dataPokemons.results.map(pokemon => {
            return (
              <div className="col-5 d-flex justify-content-between mx-5 border rounded align-items-center py-1 my-2">
                <span>{pokemon.name}</span>
                <Link href={`/pokemon/${pokemon.name}`} className="btn btn-primary">View</Link>
              </div>
            )
          })}
        </div>
        <div className='my-2 align-items-center text-center'>
          <button className='btn btn-secondary' onClick={handleLoadMore}>Load More</button>
        </div>
      </div>
      
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context:any) => {
  // const res = await fetch('https://pokeapi.co/api/v2/pokemon?offset=0&limit=20');
  // const dataPokemons = await res.json();
  
  const dataPokemons = await API.getAllPokemon();
  
  return{
    props: {
      dataPokemons,
    },
  };

  
}